name: CI

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
      - readme.md
  pull_request:

jobs:
  run-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Test random clustering across all datasets
        run: |
          python eval_entrypoint.py --method random_clustering --all
